version: '3.8'

services:
  # Serviço do Banco de Dados
  nexuscore-db:
    image: postgres:16
    container_name: nexuscore-db
    environment:
      - POSTGRES_DB=NexusCoreDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - nexuscore-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d NexusCoreDb"]
      interval: 5s
      timeout: 5s
      retries: 5
    # CONECTA O DB APENAS À REDE INTERNA.
    # Ele não é visível para o Caddy ou para o mundo exterior.
    networks:
      - nexuscore-network

  # Serviço da Aplicação Web
  nexuscore-webapp:
    container_name: nexuscore-webapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=nexuscore-db;Port=5432;Database=NexusCoreDb;Username=admin;Password=admin
    restart: on-failure
    volumes:
      - nexuscore-dataprotection-keys:/root/.aspnet/DataProtection-Keys
    # CONECTA O WEBAPP A AMBAS AS REDES.
    # Ele pode falar com o Caddy (pela caddy_network) e com o DB (pela nexuscore-network).
    networks:
      - caddy_network
      - nexuscore-network
    depends_on:
      nexuscore-db:
        condition: service_healthy

# Define os volumes nomeados
volumes:
  nexuscore-db-data:
  nexuscore-dataprotection-keys: {}

# Define as redes
networks:
  # Rede interna para comunicação entre a aplicação e o banco de dados.
  nexuscore-network:
    driver: bridge

  # Rede externa para comunicação com o proxy reverso Caddy.
  caddy_network:
    external: true
