<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NexusCore.Application\NexusCore.Application.csproj" />
        <ProjectReference Include="..\NexusCore.Domain\NexusCore.Domain.csproj" />
        <ProjectReference Include="..\NexusCore.Infra.Data\NexusCore.Infra.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MailKit" Version="4.13.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
      <PackageReference Include="OpenIddict.AspNetCore" Version="7.0.0" />
      <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.0.0" />
    </ItemGroup>

</Project>