<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NexusCore.Application\NexusCore.Application.csproj" />
		<ProjectReference Include="..\NexusCore.Infra.IoC\NexusCore.Infra.IoC.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="OpenIddict.AspNetCore" Version="7.0.0" />
		<PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.0.0" />
		<PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\libs\embla-carousel-auto-scroll\cjs\components\" />
	  <Folder Include="wwwroot\libs\embla-carousel-auto-scroll\components\" />
	  <Folder Include="wwwroot\libs\embla-carousel-auto-scroll\esm\components\" />
	  <Folder Include="wwwroot\libs\embla-carousel-autoplay\cjs\components\" />
	  <Folder Include="wwwroot\libs\embla-carousel-autoplay\components\" />
	  <Folder Include="wwwroot\libs\embla-carousel-autoplay\esm\components\" />
	  <Folder Include="wwwroot\libs\embla-carousel\cjs\components\" />
	  <Folder Include="wwwroot\libs\embla-carousel\components\" />
	  <Folder Include="wwwroot\libs\embla-carousel\esm\components\" />
	  <Folder Include="wwwroot\libs\rellax\tests\" />
	  <Folder Include="wwwroot\libs\swiper\types\modules\" />
	</ItemGroup>
</Project>
